Repository idurar/erp-crm, pull requests merged in 2023-08, with the labels that each got.

#229 Add API for Generating Invoice and Quotation Summary
  controllers/erpControllers/invoiceController.js
  controllers/erpControllers/quoteController.js
  routes/erpRoutes/erpApi.js
Labels: Backend

#340 fix: core.less issue
  frontend/src/style/partials/core.less
Labels: bug, Urgent

#369 [enhancement] organize dashboard feature to be more modular
  frontend/src/components/Dashboard/Analytics.jsx
  frontend/src/hooks/useFetch/index.jsx
  frontend/src/modules/DashboardModule/components/CustomerPreviewCard.jsx
  frontend/src/modules/DashboardModule/components/PreviewCard.jsx
  frontend/src/modules/DashboardModule/components/SummaryCard.jsx
  frontend/src/modules/DashboardModule/index.js
  frontend/src/pages/Dashboard.jsx
Labels: enhancement, Frontend
